name: Check code quality
on: [push]
jobs:
  Check_code_quality:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4
      - name: Prepare venv & install requirements
        run: |
          python3 --version
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install -r requirements_code_quality.txt
      - name: Run code quality checks
        run: |
          source venv/bin/activate
          bash code_quality.sh
