name: Unit tests
on: [push]
jobs:
  Run_unit_tests_ubuntu_22_04:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4
      - name: Install python interpreters
        run: |
          sudo apt-get update
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install   \
            python3.7            \
            python3.7-distutils  \
            python3.8            \
            python3.8-distutils  \
            python3.9            \
            python3.9-distutils  \
            python3.11           \
            python3.11-distutils \
            python3.12           \
            python3.12-distutils
      - name: Install tox
        run: |
          python3 -m pip install --user tox         
      - name: Run unit testing (on multiple python versions, using tox)
        run: |
          python3 -m tox

  Run_unit_tests_windows_2022:
    runs-on: windows-2022
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4     
      - name: Run unit testing (on a single python version)
        run: |
          python3 --version
          python3 -m pip install pytest
          bash run_unit_tests.sh
